// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        int64
	ForeignID string
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID        int64
	Email     string
	Username  sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
